# Generated by Django 4.1.7 on 2023-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_content_alter_blogpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="press",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="publish_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
