# Generated by Django 4.1.7 on 2023-04-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_enabled_blogpost_press_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
