# Generated by Django 4.2.1 on 2023-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="publish_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
