# Generated by Django 4.2.1 on 2023-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_boardunitresponse_boardunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardunitresponse",
            name="bboardunit",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.boardunit",
            ),
        ),
    ]
