# Generated by Django 4.2.1 on 2023-05-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_boardunitresponse_bboardunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardunit",
            name="btimedelta",
            field=models.TimeField(blank=True, default="00:00:00", null=True),
        ),
    ]
