# Generated by Django 4.2.1 on 2023-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_boardunit_btimedelta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardunit",
            name="btimedelta",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
