# Generated by Django 4.2.1 on 2023-05-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_boardunit_btimedelta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
    ]
