# Generated by Django 4.2.1 on 2023-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question_amount",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quiz",
            name="question_score",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_time",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="quizresultdetail",
            name="correct_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizresultdetail",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizresultdetail",
            name="user_answer_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizresultdetail",
            name="choice1_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizresultdetail",
            name="choice2_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizresultdetail",
            name="choice3_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizresultdetail",
            name="choice4_selected",
            field=models.IntegerField(default=0),
        ),
    ]
