# Generated by Django 4.2.1 on 2023-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_question_amount_quiz_question_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ManyToManyField(to="quiz.category"),
        ),
    ]
