# Generated by Django 4.2.1 on 2023-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_question_category_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                choices=[
                    ("choice1", "A"),
                    ("choice2", "B"),
                    ("choice3", "C"),
                    ("choice4", "D"),
                ],
                max_length=50,
            ),
        ),
    ]
