# Generated by Django 4.2.1 on 2023-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=50
            ),
        ),
    ]
