# Generated by Django 4.2.1 on 2023-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
