# Generated by Django 4.2.1 on 2023-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_question_question_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="explanation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
