# Generated by Django 4.2.1 on 2023-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_question_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="choice1_selected",
        ),
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="choice2_selected",
        ),
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="choice3_selected",
        ),
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="choice4_selected",
        ),
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="correct_amount",
        ),
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="question",
            name="choice1_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="choice2_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="choice3_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="choice4_selected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
    ]
