# Generated by Django 4.2.1 on 2023-05-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_remove_quizresultdetail_choice1_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="correct_amount",
            field=models.IntegerField(default=0),
        ),
    ]
