# Generated by Django 4.2.1 on 2023-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_quizresult_correct_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizresultdetail",
            name="user_answer_time",
        ),
        migrations.AddField(
            model_name="quizresult",
            name="user_answer_time",
            field=models.IntegerField(default=0),
        ),
    ]
