# Generated by Django 4.1.7 on 2023-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_user_name_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_name",
            field=models.CharField(max_length=50),
        ),
    ]
