# Generated by Django 4.1.7 on 2023-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("engineer", "Engineer"),
                    ("developer", "Developer"),
                    ("designer", "Designer"),
                    ("accountant", "Accountant"),
                    ("electrician", "Electrician"),
                    ("scientist", "Scientist"),
                    ("programmer", "Programmer"),
                    ("data scientist", "Data Scientist"),
                    ("IT consultant", "IT Consultant"),
                    ("systems analyst", "Systems Analyst"),
                    ("network administrator", "Network Administrator"),
                    ("web developer", "Web Developer"),
                    ("software engineer", "Software Engineer"),
                    ("database administrator", "Database Administrator"),
                    ("cybersecurity analyst", "Cybersecurity Analyst"),
                    (
                        "artificial intelligence specialist",
                        "Artificial Intelligence Specialist",
                    ),
                    ("robotics engineer", "Robotics Engineer"),
                    ("game developer", "Game Developer"),
                    ("mobile app developer", "Mobile App Developer"),
                    ("UI/UX designer", "UI/UX Designer"),
                    ("network engineer", "Network Engineer"),
                    ("cloud computing specialist", "Cloud Computing Specialist"),
                    ("computer systems analyst", "Computer Systems Analyst"),
                    ("IT project manager", "IT Project Manager"),
                    ("network architect", "Network Architect"),
                    ("software tester", "Software Tester"),
                    ("data analyst", "Data Analyst"),
                    ("database developer", "Database Developer"),
                    ("system administrator", "System Administrator"),
                    ("front-end developer", "Front-end Developer"),
                    ("back-end developer", "Back-end Developer"),
                    ("full-stack developer", "Full-stack Developer"),
                    ("data engineer", "Data Engineer"),
                    ("embedded systems engineer", "Embedded Systems Engineer"),
                    ("telecommunications specialist", "Telecommunications Specialist"),
                    ("VR/AR developer", "VR/AR Developer"),
                    ("blockchain developer", "Blockchain Developer"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
